// Code generated by "stringer -type=Modifier -trimprefix=Mod"; DO NOT EDIT.

package mars

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModA-0]
	_ = x[ModB-1]
	_ = x[ModAB-2]
	_ = x[ModBA-3]
	_ = x[ModF-4]
	_ = x[ModX-5]
	_ = x[ModI-6]
}

const _Modifier_name = "ABABBAFXI"

var _Modifier_index = [...]uint8{0, 1, 2, 4, 6, 7, 8, 9}

func (i Modifier) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Modifier_index)-1 {
		return "Modifier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Modifier_name[_Modifier_index[idx]:_Modifier_index[idx+1]]
}
