// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package mars

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DAT-0]
	_ = x[MOV-1]
	_ = x[ADD-2]
	_ = x[SUB-3]
	_ = x[MUL-4]
	_ = x[DIV-5]
	_ = x[MOD-6]
	_ = x[JMP-7]
	_ = x[JMZ-8]
	_ = x[JMN-9]
	_ = x[DJN-10]
	_ = x[SPL-11]
	_ = x[SEQ-12]
	_ = x[SNE-13]
	_ = x[SLT-14]
	_ = x[NOP-15]
	_ = x[LDP-16]
	_ = x[STP-17]
}

const _Opcode_name = "DATMOVADDSUBMULDIVMODJMPJMZJMNDJNSPLSEQSNESLTNOPLDPSTP"

var _Opcode_index = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54}

func (i Opcode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Opcode_index)-1 {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[idx]:_Opcode_index[idx+1]]
}
